# docke-compose.yml
version: "3"
services:
  db:
    image: postgres:latest
    restart:  always
    container_name: my-db
    hostname: myhost
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pg1234
      POSTGRES_DB: mande
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  # backend:
  #   container_name: pern_backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  # frontend:
  #   container_name: pern_frontend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   expose:
  #     - "9000"
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     FLASK_ENV: production
  

